add check for kinetis

diff --git a/.github/workflows/build-firmware.yaml b/.github/workflows/build-firmware.yaml
--- a/.github/workflows/build-firmware.yaml
+++ b/.github/workflows/build-firmware.yaml
@@ -71,7 +71,14 @@ jobs:
     - name: Generate Configs
       if: ${{ matrix.skip-config != 'yes' }}
       working-directory: ./firmware/
-      run: bash gen_config_board.sh ${{matrix.folder}} ${{matrix.build-target}}
+      run: |
+        if [ "${{ matrix.build-target }}" = "kinetis" ]; then
+          cd config/boards/kinetis/config
+          bash gen_config.sh
+          [ $? -eq 0 ] || { echo "ERROR generating board kinetis kin"; exit 1; }
+        else
+          bash gen_config_board.sh ${{matrix.folder}} ${{matrix.build-target}}
+        fi
 
     - name: Generate Live Documentation
       working-directory: ./firmware/
