wat

diff --git a/.github/workflows/build-unit-tests.yaml b/.github/workflows/build-unit-tests.yaml
--- a/.github/workflows/build-unit-tests.yaml
+++ b/.github/workflows/build-unit-tests.yaml
@@ -59,9 +59,8 @@ jobs:
         git config --local user.name "GitHub build-unit-tests Action"
         mv triggers.txt unit_tests
         mv *.logicdata  unit_tests
-        git add unit_tests/triggers.txt
         git status
-        OUT=$(git commit -m "Trigger wheel definitions" triggers.txt 2>&1) || echo "commit failed, finding out why"
+        OUT=$(git commit -m "Trigger wheel definitions" unit_tests/triggers.txt 2>&1) || echo "commit failed, finding out why"
         echo "$OUT"
         if echo "$OUT" | grep 'nothing to commit'; then
           echo "::set-env name=NOCOMMIT::true"
