Subaru_eg33: build target with no bootloader (#5357)

diff --git a/.github/workflows/build-firmware.yaml b/.github/workflows/build-firmware.yaml
--- a/.github/workflows/build-firmware.yaml
+++ b/.github/workflows/build-firmware.yaml
@@ -105,6 +105,7 @@ jobs:
             stm32f767_nucleo,
             stm32h743_nucleo,
             subaru_eg33_f7,
+            subaru_eg33_f7_no_bl,
             f407-discovery,
             f429-discovery,
             core8,
@@ -320,6 +321,11 @@ jobs:
             ini-file: rusefi_subaru_eg33_f7.ini
             skip-rate: 50
 
+          - build-target: subaru_eg33_f7_no_bl
+            folder: config/boards/subaru_eg33
+            ini-file: rusefi_subaru_eg33_f7.ini
+            skip-rate: 50
+
           - build-target: f407-discovery
             folder: config/boards/f407-discovery
             ini-file: rusefi_f407-discovery.ini
@@ -444,6 +450,9 @@ jobs:
         elif [ "${{ matrix.build-target }}" = "subaru_eg33_f7" ]; then
           bash config/boards/subaru_eg33/config/gen_subaru_config.sh
           [ $? -eq 0 ] || { echo "ERROR generating board subaru_eg33 subaru_eg33_f7"; exit 1; }
+        elif [ "${{ matrix.build-target }}" = "subaru_eg33_f7_no_bl" ]; then
+          bash config/boards/subaru_eg33/config/gen_subaru_config.sh
+          [ $? -eq 0 ] || { echo "ERROR generating board subaru_eg33 subaru_eg33_f7_no_bl"; exit 1; }
         elif [ "${{ matrix.ini-file }}" = "" ]; then
           echo "ERROR: ${{ matrix.build-target }} is missing ini-file attribute"
           exit -1
