make error more visible

diff --git a/.github/workflows/build-firmware.yaml b/.github/workflows/build-firmware.yaml
--- a/.github/workflows/build-firmware.yaml
+++ b/.github/workflows/build-firmware.yaml
@@ -288,7 +288,7 @@ jobs:
     steps:
     - name: Check branch name
       if: ${{ contains(github.ref_name, '.') }}
-      run: echo 'Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
+      run: echo '::error::Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
     - name: Execution throttle early exit
       # Don't skip any jobs if this workflow was run manually.
       if: ${{ matrix.skip-rate && github.event_name != 'workflow_dispatch' }}
@@ -449,7 +449,7 @@ jobs:
     steps:
     - name: Check branch name
       if: ${{ contains(github.ref_name, '.') }}
-      run: echo 'Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
+      run: echo '::error::Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
     - uses: actions/checkout@v3
       with:
         submodules: recursive
