only:junit usability

diff --git a/.github/workflows/build-rusEFI-console.yaml b/.github/workflows/build-rusEFI-console.yaml
--- a/.github/workflows/build-rusEFI-console.yaml
+++ b/.github/workflows/build-rusEFI-console.yaml
@@ -53,11 +53,17 @@ jobs:
         working-directory: ./java_tools
         run: ./gradlew test
 
+      - name: Publish Gradle Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+
       - name: Build console
         working-directory: ./java_console
         run: ant jar
 
-      - name: Attach console junit results
+      - name: Attach Ant console junit results
         if: always()
         uses: actions/upload-artifact@v3
         with:
