Only: output invalid branch name in GHA

diff --git a/.github/workflows/build-firmware.yaml b/.github/workflows/build-firmware.yaml
--- a/.github/workflows/build-firmware.yaml
+++ b/.github/workflows/build-firmware.yaml
@@ -157,7 +157,7 @@ jobs:
     steps:
     - name: Check branch name
       if: ${{ contains(github.ref_name, '.') }}
-      run: echo '::error::Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
+      run: echo '::error::Branch names must not contain ".", this breaks firmware autoupdates. Branch name is "${{ github.ref_name }}".' && exit 1
 
     - name: Set run condition variables 2
       run: |
diff --git a/.github/workflows/custom-board-build/action.yaml b/.github/workflows/custom-board-build/action.yaml
--- a/.github/workflows/custom-board-build/action.yaml
+++ b/.github/workflows/custom-board-build/action.yaml
@@ -88,7 +88,7 @@ runs:
       if: ${{ contains(github.ref_name, '.') }}
       run: |
         : Check branch name
-        echo '::error::Branch names must not contain ".", this breaks firmware autoupdates.' && exit 1
+        echo '::error::Branch names must not contain ".", this breaks firmware autoupdates. Branch name is "${{ github.ref_name }}".' && exit 1
 
     - name: Mask Secrets
       shell: bash
