reducing inconsistency, renaming signature header

diff --git a/.github/workflows/build-firmware.yaml b/.github/workflows/build-firmware.yaml
--- a/.github/workflows/build-firmware.yaml
+++ b/.github/workflows/build-firmware.yaml
@@ -300,7 +300,7 @@ jobs:
           [ $? -eq 0 ] || { echo "ERROR generating board kinetis kin"; exit 1; }
         elif [ "${{ matrix.build-target }}" = "cypress" ]; then
           config/boards/hellen/cypress/config/gen_cypress_config.sh
-          [ $? -eq 0 ] || { echo "ERROR generating board hellen_cypress hellen_cypress"; exit 1; }
+          [ $? -eq 0 ] || { echo "ERROR generating board cypress cypress"; exit 1; }
         elif [ "${{ matrix.build-target }}" = "subaru_eg33_f7" ]; then
           bash config/boards/subaru_eg33/config/gen_subaru_config.sh
           [ $? -eq 0 ] || { echo "ERROR generating board subaru_eg33 subaru_eg33_f7"; exit 1; }
